### PR TITLE
Feature: Update vulnerable packages

### PR DESCRIPTION
**Pull request by ckhatton**
In reference to issue #745.

I think I have gone about the package updates correctly? I just want to get the ball rolling!

### CODE REVIEW

**Comment by ckhatton** [comment]
@mde I believe Travis tests are failing on...

https://github.com/geddy/geddy/blob/master/test/scaffolding/standard.js#L65

Do you know why? I have no idea how to debug it.

**Comment by phanect** [comment]
You also need to commit package-lock.json and yarn.lock, or users still use Geddy with older dependencies.
They should be updated after you run npm update and yarn upgrade.

**Comment by ckhatton** [comment]
Thank you @phanect I have generated a new `yarn.lock` file now.

**Comment by ckhatton** [comment]
Travis was failing before because the dev package "acorn" was missing; I have now resolved it.

Now it is failing on...

> AssertionError [ERR_ASSERTION]: Error 500 when requesting http://127.0.0.1:8091

Which happens to be the port that the pug app is on.

**Comment by phanect** [comment]
Oh, I missed you have already commited updated package-lock.json.
Thanks for adding yarn.lock update.

**Comment by ckhatton** [comment]
@mde ? 😢

**Comment by mde** [comment]
My first suggestion here would be to disable the Jasmine stuff completely. We have had other cases (in Model with Riak or MySQL) where we temporarily disabled one type of adapter in the interest of getting stuff moving.

**Comment by ckhatton** [comment]
Hold up, where's the Jasmine stuff? I cannot find it anywhere in the tests. It that why Pug doesn't want to run on the test?

**Comment by mde** [comment]
Sorry, I hadn't had my coffee yet. I should have said "Jade," not "Jasmine." (Had my hipster JS projects mixed up. :P)

**Comment by ckhatton** [comment]
Haha ok.

Are you sure about removing it? I had to go through what seemed a ton of test files! (I did a find and replace which made it less taxing) Wouldn't those tests need to be rewritten in the different adapter? If so, which?

**Comment by mde** [comment]
I would not remove it; I would disable the tests for it. That way we can update it at our leisure later, and then re-enable.

**Comment by ckhatton** [comment]
Ar ok 👍 I'll try figure out how to do that.

**Comment by ckhatton** [comment]
YaY 🎉 

What significance is there that Pug (Jade) has been disabled? I am assuming because the other engines are running the tests, that it doesn't really matter Pug isn't being used ¯\_(ツ)_/¯

**Comment by mde** [comment]
This is great -- thanks for doing it. I'm going to give you the commit bit, so you can continue to make changes or improvements if you want.

**Comment by ckhatton** [comment]
> With those Pug (Jade) tests disabled, we won't know if something we have done breaks the Pug support

Well you wouldn't believe it! I've just fixed the Pug issue lol! I will create a new PR for it explaining how and why.

> I was going to say I would add you to the project. Forgot you were already set up as a contributor

Yeah, already in the game 😎

Thank you for the merge! 🤗 🙌

**Comment by mde** [comment]
Huzzah! As soon as we merge that PR that re-enables Jade/Pug, I'll push out a new release.

Thanks so much for kick-starting this!

**Comment by ckhatton** [comment]
Sorry @mde. I became distracted with selling chilli sauce. The Pug issue wasn't as fixed as I thought it was, and when I get time I will create a new issue/PR to explain what needs adding.

In a nutshell, Pug needs to know the base root of all the assets it requires and you have to pass that as an argument when initialising Pug.

**Pull request merged**
