### PR TITLE
Added plugin declaration to mailer initialization

### PR DESCRIPTION
**Pull request by flyswatter**
For me this helps solve #669, I was getting a warning since this variable was not declared.

### CODE REVIEW

**Comment by flyswatter** [comment]
I can't remotely fathom how this PR would break the test suite.

**Comment by phanect** [comment]
@flyswatter Ah, sorry, this error is caused by my change and I haven't fixed yet.

**Comment by phanect** [comment]
@flyswatter Sorry for keeping you wait. I have fixed the issue. Plz rebase your forked repo, and the test will pass.

```shell
git checkout patch-1
git remote add upstream https://github.com/geddy/geddy.git
git fetch upstream
git rebase upstream/v13
```

**Comment by phanect** [comment]
Recreated PR #695.

**Pull request closed without merging**
