### PR TITLE
added support for nodemailer transport plugins

### PR DESCRIPTION
**Pull request by hyun007**
You can use the sendgrid transport plugin by configuring mailer like so:
```javascript
    , mailer: {
        fromAddressUsername: 'noreply'
        , transport: {
            type: 'sendgrid'
            , options: {
                auth: {
                    api_user: 'sendgrid username',
                    api_key: 'sendgrid password'
                }
            }
        }
        , require: 'nodemailer-sendgrid-transport' //nodemailer transport plugin npm package name
    }
```

### CODE REVIEW

**Comment by mde** [comment]
Excellent, thanks!

**Comment by der-On** [comment]
Does this also fixes #669 ?

**Comment by hyun007** [comment]
@der-On, yes it does. I'm currently using the latest version of nodemailer

**Comment by der-On** [comment]
Great. I'll test and if it works I'll close the issue. Great work! Thanks!

**Pull request merged**
