### PR TITLE
Add 'use strict'

### PR DESCRIPTION
**Pull request by phanect**
I recommend to view diffs with `-w` option (on your git cli) or `?w=1` (on Github)

### CODE REVIEW

**Comment by phanect** [comment]
I will fix errors occurring by using strict mode.

**Comment by phanect** [comment]
Sorry, this change seem to made a test failure on Node 0.12. I'm working on it.

**Comment by mde** [comment]
This is fantastic. I am really looking forward to merging this!

**Comment by phanect** [comment]
Ah, this is already merged.
The error is only happening on Node 0.12 and io.js, so Travis didn't warned me before I merge this. Maybe I forgot to test on my local env...

**Pull request merged**
