### PR TITLE
hasOwnProperty,new release not suport

### PR DESCRIPTION
**Pull request by jaycie**
src.hasOwnProperty(p) is not be suported

### CODE REVIEW

**Comment by mde** [comment]
Good catch! This is a direct copy of the code in the `utilities` module -- I fixed it over there, but didn't realize it had been copied here. Thanks!

**Comment by mde** [comment]
Let me know if you'd like to help out -- I'd be happy to invite you to the Geddy org.

**Comment by jaycie** [comment]
@mde my pleasure

**Comment by mde** [comment]
Invitation sent! I've invited you to the Geddy Core team, which has read/write access to Geddy and Model.

**Comment by jaycie** [comment]
has been received,thanks

**Comment by ckhatton** [comment]
:+1: In the process you have helped me learn about and read about the advantage of using...

`Object.prototype.hasOwnProperty.call(object, property)`

Over...

`object.hasOwnProperty(property)`

**Pull request merged**
